### ISSUE TITLE
Documentation contains broken use of `freckle/stack-cache-action`

### ISSUE THREAD

**Issue by andreasabel** [freckle/stack-action#11]
The README gives instructions by example how to include a caching step:
https://github.com/freckle/stack-action/blob/605917bad6487161de15eea71f03163f9d37399f/README.md?plain=1#L77-L80

However, if I take this verbatim, I get a failing CI:
```
Error: ENOENT: no such file or directory, lstat 'stack.yaml.lock'
```
See e.g. https://github.com/andreasabel/miniagda/runs/6433547341?check_suite_focus=true

My repo only contains `stack.yaml` files, no `stack.yaml.lock` files.  I'd like them to be generated by the CI.

**Comment by pbrisbin** [comment]
Sorry about that! We do require the `.lock` file is present. It's a recommended practice to commit it, so we've assumed its presence. We can update the documentation to make that clear.

>  I'd like them to be generated by the CI.

I would be happy to accept a PR that somehow falls back to driving the key from the `stack.yaml` when the `.lock` is missing.

**Comment by pbrisbin** [comment]
I'm going to actually close this issue. I think we should focus the discussion where this is actually happening, in stack-cache-action.
