### ISSUE TITLE
Caching on windows?

### ISSUE THREAD

**Issue by 0rphee** [freckle/stack-action#28]
Hi! when I run the jobs on windows, ubuntu and macos, every windows build last as about the same time that the first time build of ubuntu/macos (~15min) so it seems to me that this action doesn't support _some_ windows caching (I saw some caching steps in the log). Is that the case? is windows just  consistently slower? or am I running into a problem?

In comparison, every other macos/ubuntu build takes around 1min after the first build.

**Comment by pbrisbin** [comment]
Can you share a build log? It sounds like you are inferring cache-misses based on build time, and you may be right, but we can see in the blog if caching actually missed or not.

I don't know of any _intentional_ lack of cache support on windows. It would just be a bug if it's not working.

**Comment by pbrisbin** [comment]
> I suppose they're cache misses, but I'm not that sure

To investigate, you can expand the build step and look at the 2 (dependencies, then build) `actions/cache` steps. You want to check the `key` argument to see what key each was looking for, then the actual logs to see which cache was restored. If they match exactly that means a full cache hit and there should be no build necessary. If there is some cache restored, but the restored key doesn't match exactly, that means a _partial_ cache hit and there should be some artifact reuse but also some compilation necessary -- depending on the actual change.

Linux:

```
Run actions/cache/restore@v3
  with:
    ...
    key: Linux-stack-deps-8b72ccca296d7557c917e1851110ce53a526bc0ea2c13e007ba6c4faefa3398d-4b6f817aa80b26f02cebe7e9791a3b5378f463eb482b016cc5630da090c6fa9f
    ...

...
Cache restored from key: Linux-stack-deps-8b72ccca296d7557c917e1851110ce53a526bc0ea2c13e007ba6c4faefa3398d-4b6f817aa80b26f02cebe7e9791a3b5378f463eb482b016cc5630da090c6fa9f

Run actions/cache/restore@v3
  with:
    ...
    key: Linux-stack-build-8b72ccca296d7557c917e1851110ce53a526bc0ea2c13e007ba6c4faefa3398d-4b6f817aa80b26f02cebe7e9791a3b5378f463eb482b016cc5630da090c6fa9f-d1827f44053ae294876f28993b22bbdb780f209e5c37708c3dec9c905c74be87
    ...

...
Cache restored from key: Linux-stack-build-8b72ccca296d7557c917e1851110ce53a526bc0ea2c13e007ba6c4faefa3398d-4b6f817aa80b26f02cebe7e9791a3b5378f463eb482b016cc5630da090c6fa9f-12aa29b99ad8817e5a753798dcf47e8a1e295e4d82d85902bdd069ccd0bccd56
```

Windows:

```
Run actions/cache/restore@v3
  with:
    ...  
    key: Windows-stack-deps-5e2e8ac5295e547248aa5c37d8d78f5e8d2d2eec6eda0e19285e6e8d7f2a5445-e7a5ab2e2fb3775e618b645236d4ef2a1dc5233f175ec7b0055c73ec20659ecc
    ...

...
Cache restored from key: Windows-stack-deps-5e2e8ac5295e547248aa5c37d8d78f5e8d2d2eec6eda0e19285e6e8d7f2a5445-e7a5ab2e2fb3775e618b645236d4ef2a1dc5233f175ec7b0055c73ec20659ecc

Run actions/cache/restore@v3
  with:
    ...
    key: Windows-stack-build-5e2e8ac5295e547248aa5c37d8d78f5e8d2d2eec6eda0e19285e6e8d7f2a5445-e7a5ab2e2fb3775e618b645236d4ef2a1dc5233f175ec7b0055c73ec20659ecc-564a422d9fc8ce73f475a8eba307ff4832cf616de2848545be742d5f6f0a8e45
    ...

...
Cache restored from key: Windows-stack-build-5e2e8ac5295e547248aa5c37d8d78f5e8d2d2eec6eda0e19285e6e8d7f2a5445-e7a5ab2e2fb3775e618b645236d4ef2a1dc5233f175ec7b0055c73ec20659ecc-978a713f414ba4774ad25464f70169712e7229748e187717555c6f108b91a2d9
```

Both of these are behaving the same: the dependencies cache was a full hit (so there should be no need to install GHC or any dependency packages), but we have only a partial cache hit on the build step (indicating this commit has some source differences from the one that produced that cache). Depending on what actually changed, there may be some building necessary. In this case, I see the commit contains a non-Haskell change so I would still expect no building.

The Linux build behaves correctly and doesn't build anything, but the Windows build proceeds to do _all_ the work again.

Unfortunately, I'm not sure where to go from here. The action seems to behaving correctly, but either `actions/cache` is storing something invalid or `stack` is misbehaving (or some combination) when used on Windows. It seems unlikely there is a bug in our action, although there may be some workaround we could implement, but I'm just not sure how to debug it further. If you're motivated, my only idea would be to make a workflow that performs the underlying caching and build steps of our action then see if it reproduces. If so, it would be possible to inject logging or other debugging mechanisms at that point.

**Comment by 0rphee** [comment]
Sorry for the late response... I forgot about this. 

I think I just assumed that there was no cache hit on Windows because stack built everything from scratch, unlike the builds from the other OS'es. Anyways, I think I'm gonna leave it here. Thanks anyway!
