### ISSUE TITLE
Allow pedantic to be optional

### ISSUE THREAD

**Issue by parsonsmatt** [freckle/stack-action#3]
I'm trying to use this with `persistent`, which has a lot of redundant imports and warnings from deprecations and other GHC versions. `pedantic` being a fixed option makes it difficult to support these things.

A work around is to provide `--ghc-options "-Wwarn"` in the `stack-arguments` section.

**Comment by pbrisbin** [comment]
Good idea, will do.

**Comment by pbrisbin** [comment]
I'm surprised `--no-pedantic` isn't also something you could add in `stack-arguments` :thinking: Either way, making it an option in the Action makes total sense to me.
