### ISSUE TITLE
Error: The process '/Users/runner/.ghcup/bin/stack' failed with exit code 1

### ISSUE THREAD

**Issue by hanjoosten** [freckle/stack-action#51]
I use the `main` version of stack-action. Recently this caused an error, as can be seen in [this log](https://github.com/AmpersandTarski/Ampersand/actions/runs/7783988346/job/21788803189).

In a [comment of some other issue](https://github.com/commercialhaskell/stack/issues/6477#issuecomment-1958166248) it is suggested that if ghcup is used, one mustn't use `stack upgrade`.

**Comment by pbrisbin** [comment]
You can avoid `stack upgrade` by using `with.upgrade-stack: false`. That said, the upgrade didn't actually do anything because there was no new version available. Your workflow also seemed to only fail on macOS, with the Linux builds working fine. Also, there seems to be no actual error, it just reports that `stack` exited 1... :thinking: 

Can you re-run with Debug and see if you can get more detail?

**Comment by hanjoosten** [comment]
@pbrisbin Thanks for looking into this. I just started the rerun with Debug. The [log is here](https://github.com/AmpersandTarski/Ampersand/actions/runs/7783988346/job/21865132966)

**Comment by hanjoosten** [comment]
It is complaining about the `--flag` option. Very strange, since on windows and Linux that is no issue.

**Comment by pbrisbin** [comment]
Yeah, I see that too:

```
  /Users/runner/.ghcup/bin/stack --stack-yaml stack.yaml --copy-bins --flag ampersand:buildAll path --stack-root
  Invalid option `--flag'
  
  Usage: stack [--help] [--version] [--numeric-version] [--hpack-numeric-version] 
               [--docker*] [--nix*] 
               [--verbosity VERBOSITY | (-v|--verbose) | --silent] 
               [--[no-]time-in-log] [--[no-]rsl-in-log] [--[no-]plan-in-log] 
               [--stack-root STACK-ROOT] [--work-dir WORK-DIR] [--[no-]system-ghc]
               [--[no-]install-ghc] [--arch ARCH] [--ghc-variant VARIANT] 
               [--ghc-build BUILD] [-j|--jobs JOBS] [--extra-include-dirs DIR] 
               [--extra-lib-dirs DIR] [--custom-preprocessor-extensions EXT] 
               [--with-gcc PATH-TO-GCC] [--with-hpack HPACK] 
               [--[no-]skip-ghc-check] [--[no-]skip-msys] [--local-bin-path DIR] 
               [--setup-info-yaml URL] [--[no-]modify-code-page] 
               [--[no-]allow-different-user] [--[no-]dump-logs] 
               [--color|--colour WHEN] [--snapshot-location-base URL] 
               [--[no-]script-no-run-compile] [--resolver|--snapshot SNAPSHOT] 
               [--compiler COMPILER] [--[no-]terminal] 
               [--stack-colors|--stack-colours STYLES] [--terminal-width INT] 
               [--stack-yaml STACK-YAML] [--lock-file ARG] COMMAND|FILE
```

This is coming from your setup,

```yaml
  with:
     stack-arguments: --copy-bins --flag ampersand:buildAll
```

I also don't understand why this is fine on other OSs -- but it seems unrelated to the action?

**Comment by pbrisbin** [comment]
Well, I can tell you `stack-arguments` are for _global_ arguments to be used for every invocation of `stack` (like `--stack-yaml`). Options like `--copy-bins` and `--flag` should be passed in `stack-build-arguments`.

https://github.com/freckle/stack-action?tab=readme-ov-file#notable-changes-in-v5

That should fix it.

**Comment by hanjoosten** [comment]
Hmm. I see what you mean. However, if I change that in my .yaml file, I get an error:
![image](https://github.com/freckle/stack-action/assets/1159672/f87fa03b-a5c7-40e7-92ff-d8b86a5814e8)

**Comment by hanjoosten** [comment]
Now it seems fine. Thanks again!
