### ISSUE TITLE
stack test fails on Windows

### ISSUE THREAD

**Issue by deemp** [freckle/stack-action#56]
I have an action that fails on Windows  on `stack test` with a non-informative error.

```
eo-phi-normalizer> spec.exe: <stdout>: commitBuffer: invalid argument (cannot encode character '\10214')
```

https://github.com/objectionary/normalizer/actions/runs/8152594586/job/22282343404#step:3:111

I read https://stackoverflow.com/a/63751678.

Setting `LC_ALL=C.UTF-8` didn't help.

https://github.com/objectionary/normalizer/pull/98/commits/32501dca718d00b025b02900f1bec3e49e3d6708

I tried debugging it by disabling tests and running `tmate` right after `stack-action`.

https://github.com/objectionary/normalizer/pull/98/commits/0637f1cfbda9aadd4e30749c5729fd496a02f33f

```yaml
- name: Setup tmate session
  uses: mxschmitt/action-tmate@v3
```

I connected to a windows runner and ran `stack`.

I got the same error as in previous runs.

I ran `chcp.com 65001` as recommended ([link](https://stackoverflow.com/a/50476493)).
Then, I ran `stack test` and it worked.

**Comment by pbrisbin** [comment]
Are you suggesting we should run `chcp.com 65001` automatically if on Windows?

Is this always needed, or only for certain projects / source files? If it's always needed, why is it suddenly failing now, why not in our test suite? If it's only needed for certain projects / source files, what is it that makes it necessary? Is it reasonable to document and require users run that command themselves?

If someone who just does `run: stack test` would encounter this, which it seems like is the case, then I don't think we can call it a bug in the action. Then, the question becomes how reasonable is it to have the action do things to compensate for it, I guess.

**Comment by deemp** [comment]
I'm yet to solve this problem. Let's keep this issue open for a week. If I find a solution, I'll share it and then we can decide if it's reasonable to incorporate it into stack-action (and provide an input flag).

**Comment by deemp** [comment]
So, you use actions/exec. It uses child_process.spawn().

https://github.com/actions/toolkit/blob/b807fc9c541224508f753d1cc8a18c66072c181e/packages/exec/src/toolrunner.ts#L437

Some advice (not a complete solution).

https://stackoverflow.com/a/59635209

**Comment by deemp** [comment]
I resolved this issue as follows:

1. Test after `stack-action` in a `bash` shell ([link](https://github.com/objectionary/normalizer/blob/22332399b9ae4832fcd6763679caffb1f138c9ba/.github/workflows/ghc.yml#L82)).
1. Add `chcp 65001` in `Setup.hs` when building on Windows ([link](https://github.com/objectionary/normalizer/blob/22332399b9ae4832fcd6763679caffb1f138c9ba/eo-phi-normalizer/Setup.hs#L33)).
1. Make the command in `Setup.hs` single-line ([link](https://github.com/objectionary/normalizer/blob/22332399b9ae4832fcd6763679caffb1f138c9ba/eo-phi-normalizer/Setup.hs#L32)).
    - [ ] TODO why didn't a multiline command work?
1. Run tests in a `bash` shell with `chcp 65001` before `stack test` ([link](https://github.com/objectionary/normalizer/blob/22332399b9ae4832fcd6763679caffb1f138c9ba/.github/workflows/ghc.yml#L85)).
1. Force `stack` to run `Setup.hs` ([link](https://github.com/objectionary/normalizer/blob/22332399b9ae4832fcd6763679caffb1f138c9ba/.github/workflows/ghc.yml#L86-L87)). Otherwise, some modules weren't generated by `bnfc`.
   - [ ] TODO add option to `stack-action` that controls running `stack clean` after restoring dependencies and before `stack build`.
1. Use `withUtf8` from [with-utf8](https://hackage.haskell.org/package/with-utf8) both in the app ([link](https://github.com/objectionary/normalizer/blob/22332399b9ae4832fcd6763679caffb1f138c9ba/eo-phi-normalizer/app/Main.hs#L355)) and tests ([link](https://github.com/objectionary/normalizer/blob/22332399b9ae4832fcd6763679caffb1f138c9ba/eo-phi-normalizer/test/Main.hs#L8)).

**Comment by pbrisbin** [comment]
Just curious, does it not work to do:

```yaml
      - name: Fix for Windows
        if: ${{ runner.os == 'Windows' }}
        run: chcp.com 65001

      - name: Test
        uses: freckle/stack-action@v5
        with:
          stack-build-arguments: --pedantic --prefetch --copy-bins
```

?

**Comment by deemp** [comment]
No, it's not enough.

If I don't run `chcp.com 65001` ([link](https://github.com/deemp/normalizer/actions/runs/9118672335/job/25072334586#step:5:103)), `alex` throws an error ([link](https://github.com/deemp/normalizer/actions/runs/9118672335/job/25072334586#step:5:102)).

**Comment by pbrisbin** [comment]
Hmm, I may not be being clear, or maybe I'm confused.

In your earlier links, I thought you were doing:

- `stack-action` with `test: false`
- `stack clean`
- `chcp.com 65001`
- `stack test`

> If I don't run `chcp.com 65001`...

I'm not suggesting you don't run it, I'm suggesting you run it before stack entirely:

- `chcp.com 65001`
- `stack-action` with `test: true`

I don't see how build-clean-chcp-test works, but chcp-test wouldn't -- build-clean are kind of offsetting actions in my mind.

**Comment by pbrisbin** [comment]
Oh I see in your build log now that you indeed did that.

I wonder if the cache-restore undoes it, which is why doing a clean-chcp after works but doing the chcp before doesn't.

**Comment by deemp** [comment]
Here's a better run.

The code page is 65001 in cmd.exe [link](https://github.com/deemp/normalizer/actions/runs/9119024774/job/25073500848#step:4:5).

However, it's not in Setup.hs [link](https://github.com/deemp/normalizer/actions/runs/9119024774/job/25073500848#step:5:78).

**Comment by deemp** [comment]
And here you can see that `--reconfigure` ([link](https://github.com/deemp/normalizer/actions/runs/9119154939/job/25073919373#step:5:63)) doesn't force `stack` to run `Setup.hs`, so some modules aren't generated and the action fails ([link](https://github.com/deemp/normalizer/actions/runs/9119154939/job/25073919373#step:5:83)). I'm not sure whether it's intended.

**Comment by pbrisbin** [comment]
> The code page is 65001 in cmd.exe [link](https://github.com/deemp/normalizer/actions/runs/9119024774/job/25073500848#step:4:5).
>
> However, it's not in Setup.hs [link](https://github.com/deemp/normalizer/actions/runs/9119024774/job/25073500848#step:5:78).

I'll admit I don't know exactly what `chcp` does, but if it's modifying files and those files are then overwritten by a cache-restore, it would make sense that its effect is undone. It would also make sense that doing a `clean` and then `chcp` again would make it work correctly. Do you agree that may be what's happening, or no?

If you set a `cache-prefix` and tried it that way again but without any caching, I suspect it might work then.

> --reconfigure ([link](https://github.com/deemp/normalizer/actions/runs/9119154939/job/25073919373#step:5:63)) doesn't force stack to run Setup.hs

I don't know anything about this, but I do see that your `--reconfigure` flag is passed onto `stack` correctly. So, if this is some kind bug, it's in `stack` and not `stack-action`.

**Comment by deemp** [comment]
> it would make sense that its effect is undone

Seems like the active code page is shared at any level in a process.

```
runneradmin@fv-az521-811 MINGW64 /d/a/normalizer/normalizer
# chcp.com
Active code page: 437

runneradmin@fv-az521-811 MINGW64 /d/a/normalizer/normalizer
# cmd 
Microsoft Windows [Version 10.0.20348.2461]
(c) Microsoft Corporation. All rights reserved.

D:\a\normalizer\normalizer>cmd /c cmd /c chcp 65001
Active code page: 65001

D:\a\normalizer\normalizer>chcp
Active code page: 65001

D:\a\normalizer\normalizer>exit

runneradmin@fv-az521-811 MINGW64 /d/a/normalizer/normalizer
# chcp.com
Active code page: 65001
```

However, I'm not sure `stack-action` is aware of this code page.

> if this is some kind bug, it's in stack

Yes, and it can be solved via `stack` ([link](https://docs.haskellstack.org/en/stable/faq/#why-doesnt-stack-rebuild-my-project-when-i-specify-ghc-options-on-the-command-line)), as I've just found.

**Comment by deemp** [comment]
> However, I'm not sure stack-action is aware of this code page.

It is ([link](https://github.com/deemp/normalizer/actions/runs/9119632261/job/25075421271#step:6:138)).

**Comment by pbrisbin** [comment]
> However, I'm not sure stack-action is aware of this code page

This sentence confused me. `stack-action` just runs commands with `exec`. Are you saying `exec` may not be "aware"?

> ```
>  C:\Windows\system32\cmd.exe /c chcp && stack --no-terminal build --test --no-run-tests --dependencies-only --pedantic --prefetch --copy-bins --ghc-options -O2 --reconfigure
>  Active code page: 65001
>  Error: [S-922]
>  No cryptographic hash found for Hackage package BNFC-2.9.5, updating
>  Selected mirror https://hackage.haskell.org/
>  Downloading root
>  
>  Error: [S-922]
>         No cryptographic hash found for Hackage package Glob-0.10.2.
```

Does the "Active code page: 65001" here indicated that avoiding a cache-restore _did_ make it behave correctly? And that this build should've passed if the (unrelated) "No cryptographic hash" error didn't happen?

**Comment by deemp** [comment]
Yes, I thought `exec` may be unaware.

Yes, the error is irrelevant.

**Comment by deemp** [comment]
The error was due to [--prefetch](https://github.com/commercialhaskell/stack/issues/5435).

**Comment by deemp** [comment]
For some reason, after I've set the code page ([link](https://github.com/objectionary/normalizer/actions/runs/9127913999/job/25099233001#step:3:7)) to 65001, the code page in the `Setup.hs` script is 437 ([link](https://github.com/objectionary/normalizer/actions/runs/9127913999/job/25099233001#step:6:84)), so I have to set it to 65001 again.

Offtopic: I documented some others weird things about Windows runners ([link](https://github.com/objectionary/normalizer/issues/347#issuecomment-2117097070)).

**Comment by deemp** [comment]
So, `stack-action` works OK, and I can finally close this issue.

**Comment by pbrisbin** [comment]
OK, so let me confirm some basic facts:

1. For some class of windows builds, a `chcp` needs to be run for the build to succeed
2. If the `chcp` is run and then a cache is restored, it's undone (build fails)
3. If the `chcp` is run and then a cache is NOT restored, it's NOT undone (build succeeds)
4. If you add the `chcp` to your own `Setup.hs` [all is OK](https://github.com/objectionary/normalizer/actions/runs/9127913999/job/25099233001#step:3:7), without any stack-action changes needed

?

**Comment by deemp** [comment]
1. `chcp` is necessary for commands that output Unicode. In our case, tests output Unicode ([link](https://github.com/deemp/normalizer/actions/runs/9130555546/job/25107726243#step:6:282)).
1. If the `chcp` is run before `stack-action` and a cache is restored, tests may not need to build ([link](https://github.com/deemp/normalizer/actions/runs/9130430285/job/25107335586#step:6:85)) and they succeed.
1. If the `chcp` is run before `stack-action` and then a cache is restored and then `stack` is run, `stack` runs with `65001` ([link](https://github.com/deemp/normalizer/actions/runs/9130555546/job/25107726850#step:6:91)). So, cache restoration doesn't affect the code page.
1. If I don't add `chcp 65001` to my `Setup.hs`, the code page is 437 ([link](https://github.com/deemp/normalizer/actions/runs/9130555546/job/25107726850#step:6:106)) and tests fail.
1. If I add `chcp 65001`, tests succeed ([link](https://github.com/objectionary/normalizer/actions/runs/9127913999/job/25099232795#step:6:96)) because then, `bnfc`, `alex` and `happy` read and write UTF-8.
