### ISSUE TITLE
Unexplainable delay after "Set outputs"

### ISSUE THREAD

**Issue by deemp** [freckle/stack-action#57]
What time-consuming activity happens after "Set outputs" is printed? I couldn't grasp from the code immediately.

![image](https://github.com/freckle/stack-action/assets/48378098/006788ec-fab3-40e7-8e65-fa78e2d5c8f2)

https://github.com/freckle/stack-action/actions/runs/8108910449/job/22163043510#step:3:546

**Comment by pbrisbin** [comment]
I saw that too, but it seemed intermittent and something happening on the runner that I couldn't observe. Even with debug enabled we're done all of our work before the delay happened. I would love to get to the bottom of this.

My memory is fuzzy, but I think it happened when we had a cache miss but not when we had a cache hit?

**Comment by deemp** [comment]
@pbrisbin, please reopen this issue (I can't). #69 hasn't solved it, unfortunately
