### ISSUE TITLE
Consider using `stack path` instead of custom logic

### ISSUE THREAD

**Issue by deemp** [freckle/stack-action#60]
Related to #33

stack 2.15.3 with fixes to stack `path` behavior is released ([link](https://github.com/commercialhaskell/stack/issues/6484#issuecomment-1983194215)).

`stack path --programs` shouldn't require ghc now ([link](https://github.com/commercialhaskell/stack/commit/93a7bd8104310caaf89d2e84e6095c4dcf844447#diff-874f33563125619a7a5cb567ebe523c59258662d69858d78d24d947b275f9c6c)).

**Comment by pbrisbin** [comment]
:tada: since we do a `stack upgrade` (by default), it should be safe to do this at any point. No need to wait for GitHub runners to catch up.
