### ISSUE TITLE
Error: The process '/usr/local/bin/stack' failed with exit code 1

### ISSUE THREAD

**Issue by hanjoosten** [freckle/stack-action#66]
I use stack-action@v5 to build my project in a GitHub action. However, it fails to build in the step `Determine stack directories` without giving a reason:

~~~
Determine stack directories
Error: Error: The process '/usr/local/bin/stack' failed with exit code 1
Error: The process '/usr/local/bin/stack' failed with exit code 1.  
~~~

If I build the program in my dev environment, I also use stack and it builds fine.

The log can be found [here](https://github.com/AmpersandTarski/Ampersand/actions/runs/8329359003/job/22791471373?pr=1474).

**Comment by hanjoosten** [comment]
Sorry for your time, @pbrisbin . I have been very stupid, for I ran into this very issue last month as well. See https://github.com/freckle/stack-action/issues/51

**Comment by pbrisbin** [comment]
Ah no worries. It is unfortunate that when we're parsing (and hiding) output, you don't get to see it when it fails, which would make such issues obvious. It would be a little complex to do things in a way that we could, but perhaps worth it.
