### ISSUE TITLE
Improve error message about the missing stack executable

### ISSUE THREAD

**Issue by deemp** [freckle/stack-action#80]
## Problem

Currently, some `macos-*` GitHub runner images don't have `stack` installed. E.g, `macos-latest` aka `macos-14` ([link](https://github.com/actions/runner-images/blob/6467c6dfc24084b01e38a45bc627775d0749cd76/images/macos/macos-14-Readme.md)).

Currently, the `stack-action` tries to run `stack` and just fails ([link](https://github.com/objectionary/normalizer/actions/runs/8874674767/job/24362571195#step:3:18)).

## Possible solutions

- Check whether `stack` is missing. If it's missing, don't run the action and provide a helpful message, e.g., a message that recommends to check the current runner image.
- Install `stack` if missing, cache it.
  - `stack` may be unavailable for a particular image for good reasons.

**Comment by pbrisbin** [comment]
Thanks for reporting this, we've hit it too.

For those coming across this Issue, until we decide a solution, here is a workaround:

```diff
+ - if: ${{ runner.os == 'macOS' }}
+   run: curl -sSL https://get.haskellstack.org/ | sh
  - uses: freckle/stack-action@vX
```

I'm a bit conflicted. On the one hand, I think `stack-action` should Just Do It, which means install if necessary. On the other, that `run:` stanza is *very easy*, so keeping the complexity out of here (and adding only a clearer error message) is a pretty attractive option.

What might tip the scales is what, concretely, it would look like to do the equivalent `curl|sh` from within JavaScript. If it's easy, alright let's do it. If it's annoying to run commands and pipe output to other processes like that, I'd hesitate.

Either way, I don't think we need any caching. That `curl|sh` is just pulling a binary, so caching the same binary to then pull it from there instead would not be any faster, and only add the time to save it.

**Comment by pbrisbin** [comment]
Well, I've got https://github.com/freckle/stack-action/pull/81 now. WDYT?

**Comment by deemp** [comment]
I think it's neat!

I see installing `stack` takes a couple of seconds ([link](https://github.com/freckle/stack-action/actions/runs/8924567863/job/24511168765#step:3:11)), so caching `stack` is indeed unnecessary.

**Comment by pbrisbin** [comment]
Done in v5.3.0.

**Comment by deemp** [comment]
Thank you! Please add the tag to Releases.

**Comment by pbrisbin** [comment]
Huh, something is weird here because I thought I did:

```console
% git tag | sort -rV | head -n 1
v5.3.0
% g push --follow-tags
Everything up-to-date
```

And yet, it's indeed not visible on https://github.com/freckle/stack-action/tags.

:thinking:

**Comment by pbrisbin** [comment]
Should be fixed now. I did a `push --tags` instead of `--follow-tags`. Unclear why the difference this time.
